apiVersion: apps/v1
kind: Deployment
metadata:
  name: lakshya.com
  labels:
    app: lakshya-app
spec:
  selector:
    matchLabels:
        app: lakshya-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lakshya-app
    spec:
      containers:
        - name: lakshya-app
          image: lakshya0102/lakshya0102:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
